# Generated by Django 3.2.7 on 2021-09-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetable',
            name='pt_title',
            field=models.CharField(max_length=200, verbose_name='Услуга'),
        ),
    ]
